### ISSUE TITLE
Compile error <cannot declare field 'DisplayUI::display' to be of abstract type 'SSD1306Wire'>

### ISSUE THREAD

**Issue by agus0** [LmfaoHax/Heltec-deauther#1]
Hello! when i try to compile using Arduino 1.8.20 in windows 11 it gives me the error mentioned in the title, i followed all the steps of the main branch (install card in the IDE).
I don't understand what is happening.
Thanks

**Comment by LmfaoHax** [comment]
Hello there
Did you follow the steps from this version of deauther readme or the new
one?
Because i havent updated it since and to get it to work you should use
libraries' version match to This particular older version of deauther.
If you still had trouble to find the right ones and match them for
compiling, let me know so ill check them out myself
⚠️ALSO make sure to make your IDE use use SSD1306 and SSD1306Wire headers
from "./esp8266_deauther" NOT the ones already installed on your IDE⚠️

**Comment by LmfaoHax** [comment]
Let me know i you want me to upload my own versions of libraries needed to compile this version of deauther
